POST https://node-do-zero-n0q1.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o video node",
    "duration": 180
}

###

GET  https://node-do-zero-n0q1.onrender.com/videos

###

PUT https://node-do-zero-n0q1.onrender.com/videos/e43cbbd6-ab00-49fd-a702-ea492c8ee573
Content-Type: application/json

{
    "title": "Video 04",
    "description": "Esse é o video 04",
    "duration": 180
}

###

DELETE https://node-do-zero-n0q1.onrender.com/videos/e43cbbd6-ab00-49fd-a702-ea492c8ee573